export default [
  {
    id: 1,
    title: 'cool article',
    paragraphs: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum hendrerit, nibh ut pharetra fringilla, augue nisl sodales ante, at elementum justo nunc vel mauris. Aenean mi est, feugiat vitae est eget, dictum finibus velit. Praesent dignissim quis lectus ut bibendum. Praesent commodo felis ut pharetra semper. Nunc nec rutrum ligula. Aliquam cursus felis tellus, vel fringilla turpis commodo in. In sit amet magna ornare, lacinia ipsum at, facilisis metus. Morbi semper, ligula sit amet bibendum ornare, sem purus lacinia orci, sit amet posuere purus arcu ut nulla. Donec finibus nisl quam. Proin blandit ornare ipsum, ac pellentesque lacus laoreet id.',
      'Nulla facilisi. Pellentesque pellentesque eget ligula id rutrum. Aenean at turpis pretium nisl feugiat ultrices eu in mauris. Vestibulum rhoncus leo porta leo ornare auctor. Praesent fringilla convallis mollis. In libero mi, lobortis non mattis sed, dapibus quis mauris. Aenean facilisis imperdiet velit, et facilisis nibh pretium id. Donec ac molestie leo. Quisque iaculis ligula elit, in auctor nisl tristique eget. Maecenas commodo scelerisque diam a accumsan. Pellentesque in dapibus erat. Vivamus in eros sit amet ante lobortis placerat mollis id metus.',
      'Aliquam vehicula enim lorem, a mollis nunc posuere eget. Vestibulum felis sem, pellentesque et finibus eget, cursus quis lectus. Vestibulum fringilla neque quis metus egestas mattis. Sed placerat tortor nec efficitur mollis. Vivamus hendrerit viverra commodo. Praesent congue diam lorem, id suscipit metus vulputate sit amet. Quisque molestie, ligula et condimentum vulputate, nisl sapien efficitur magna, ac rhoncus neque ex a sem. Nunc semper nunc ac erat placerat, et efficitur nulla facilisis.',
      'Suspendisse et felis faucibus, consequat elit nec, ultricies urna. Fusce nibh ex, lobortis eget nibh sit amet, dignissim tincidunt velit. Cras pellentesque eu risus sit amet placerat. Proin id aliquet metus. Phasellus et sem ac nulla semper accumsan quis ac ligula. Maecenas at diam suscipit, vestibulum orci et, convallis urna. Sed dignissim massa sit amet mi maximus, non semper magna placerat. Integer viverra sed dui nec molestie. Cras pretium dolor a dictum interdum. Cras tincidunt facilisis lectus. Praesent feugiat tellus at metus vestibulum tristique.',
      'Cras justo ipsum, pulvinar ac nulla id, gravida rhoncus erat. Nunc at maximus sem. Ut eu libero pharetra, imperdiet tellus et, iaculis nulla. Sed dignissim aliquet nulla, in sollicitudin metus consequat eu. Duis et sapien dolor. Donec fermentum, ante eu mattis consequat, felis purus blandit ipsum, a ornare ex dui ut erat. Phasellus at consectetur purus. Nulla facilisi. Quisque eu neque nulla. Ut sodales, felis sit amet bibendum tincidunt, urna magna eleifend lacus, sed maximus lectus lectus nec mi. Cras interdum vel mi sed cursus. Aenean sollicitudin scelerisque mattis. Proin consequat et urna et vehicula.'
    ]
  }
];
